apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-prod
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-prod.yaml
    path: argocd-exercises/helm/nginx
    repoURL: https://github.com/barbietunnie/udacity-cloud-native-application-architecture
    targetRevision: HEAD